### ISSUE TITLE
Dont working on heroku

### ISSUE THREAD

**Issue by ghost** [c0ldplasma/bonfire#9]
![Screenshot_20210607-151358_Chrome](https://user-images.githubusercontent.com/74503503/121068849-220ff580-c7a3-11eb-86cf-9a70f6ee90ab.jpg)
--------
I tried to deploy this on heroku, and I get this after i authorize my twitch

**Comment by c0ldplasma** [comment]
To host it yourself on a Server you need to create your own ClientID through the Twitch Development website and enter the URL where the website is deployed. After that replace ClientID and the URL in src/app/TwitchConstants.js 

Just a Note: The last real update to this project was in 2019, so all ne chat features introduced after that are not working.
